# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 35d8ea3de7a58a2f4da7b3957c5aa5ed5c2b3ea1419b54742a2d99727ced56eae95dc9ab0237fb4959a51bc99926e910de718d3773841fa30fd9ff8df9b28336

test:
  secret_key_base: 47267f48ecda4463d5370705d4b2ebec6da25e9b67da54b95ce08215f987d17f2c51a6c31060e9ee700df7faa1db14c46651978ff3aa06a14861e197872f315c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
